name             'opennebula_ng'
maintainer       'Chris Aumann'
maintainer_email 'me@chr4.org'
license          'Apache License, Version 2.0'
description      'Installs/Configures opennebula_ng'
long_description 'Installs/Configures opennebula_ng'
version          '0.2.0'
supports         'debian'
supports         'ubuntu'
depends          'apt'
depends          'nfs'
depends          'mysqld'
